---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-models-pv
spec:
  capacity:
    storage: 1000Gi  # Arbitrary value for S3
  accessModes:
    - ReadOnlyMany
  mountOptions:
    - allow-delete
    - region us-west-2
    - prefix models/
    - metadata-ttl 20
  csi:
    driver: s3.csi.aws.com
    volumeHandle: comfyui-models-bucket-008971666757  # Your S3 bucket name
    volumeAttributes:
      bucketName: comfyui-models-bucket-008971666757
      cache: emptyDir
      cacheEmptyDirSizeLimit: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models-pvc
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1000Gi
  volumeName: comfyui-models-pv

